### ISSUE TITLE
please deploy on nuget

### ISSUE THREAD

**Issue by ignatandrei** [brecht-vde/lucide-blazor#9]
I maintain a list of .NET RSCG at https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG

I want to add your package - but please deploy on Nuget also to be easy to install

Thanks

**Comment by RamonMeffert** [comment]
Seconding this :)

**Comment by matengo** [comment]
Why not on Nuget?

**Comment by ignatandrei** [comment]
So ?

**Comment by brecht-vde** [comment]
Hi,

Thank you for your interest. I would like to point out, this repository was meant for myself to discover how source generators in C# work. It is no longer maintained. Nevertheless, I've uploaded the last release on Nuget (unlisted), should that still serve a purpose for you: https://www.nuget.org/packages/Lucide.Blazor/

Kind regards,
Brecht

**Comment by ignatandrei** [comment]
To function as generator, it should be into analyzers/dotnet/cs/

https://ignatandrei.github.io/RSCG_Examples/v2/docs/GoodPractices#ensure-in-nuget
